/**
 * contract-api.ts — typed wrapper around the compiled event-tickets contract.
 *
 * ⚠️  SSR WARNING — Never statically import this file in a Next.js page.
 * Always use dynamic import() inside an async function:
 *
 *   async function handleDeploy() {
 *     const { EventTicketAPI } = await import("@/sdk/contract-api");
 *     // ...
 *   }
 *
 * ─── Architecture note ────────────────────────────────────────────────────
 *
 * The compiled contract module lives at:
 *   <project-root>/generated/managed/event-tickets/contract/index.cjs
 * It is generated by:
 *   cd contract && make build
 * then copied to the frontend's /public dir:
 *   cd contract && make copy-to-frontend
 *
 * Because the path does not exist until after compilation, all imports of
 * that module are done lazily inside `getContractModule()`.
 *
 * ─── Package note ─────────────────────────────────────────────────────────
 *
 * The pattern below uses `CompiledContract` from `@midnight-ntwrk/compact-js`.
 * If that package is not resolvable, try `@midnight-ntwrk/compact-runtime`
 * as an alternative source for the same export.
 *
 * TODO: once the exact package name is confirmed against the installed
 *       @midnight-ntwrk/* version set, remove this note and fix the import.
 */

// eslint-disable-next-line @typescript-eslint/no-require-imports
const midnightContracts = require("@midnight-ntwrk/midnight-js-contracts");
const { deployContract, findDeployedContract } = midnightContracts;

import type { MidnightProviders } from "@midnight-ntwrk/midnight-js-types";
import type {
  DeployResult,
  EventState,
  IssueTicketResult,
  TicketSecret,
  VerifyTicketResult,
} from "./types.js";

// ─── Compiled contract module (lazy-loaded) ───────────────────────────────

// Type stub for the generated contract module.  The real types are produced
// by `compact compile` and live in generated/managed/event-tickets/contract/.
type ContractModule = {
  Contract: new () => unknown;
  ledger: unknown;
  Witnesses: unknown;
};

let _module: ContractModule | null = null;

async function getContractModule(): Promise<ContractModule> {
  if (_module) return _module;
  try {
    // Path is relative to the SDK build output; adjust if your build tool
    // changes the output location.
    _module = (await import(
      "../../generated/managed/event-tickets/contract/index.cjs"
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    )) as any;
  } catch (err) {
    throw new Error(
      "Could not load compiled contract module.  " +
        "Run `cd contract && make build` then `make copy-to-frontend` first.\n" +
        String(err),
    );
  }
  return _module!;
}

// ─── Pallas scalar-field prime ────────────────────────────────────────────
// Midnight uses the Pallas curve whose scalar field has this prime.
// Used by pubkeyToField() to reduce the public-key bytes into a field element.
//
// TODO: Verify the exact field prime against Midnight's published curve
//       parameters.  If Midnight uses a different curve or prime, update
//       this constant and all callers.
const PALLAS_SCALAR_PRIME =
  0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001n;

/**
 * Convert a 32-byte shielded public key (Bytes<32>) to a Field element.
 *
 * Interprets the bytes as a little-endian unsigned integer and reduces
 * modulo the Pallas scalar-field prime.  This matches the encoding the
 * Compact circuit expects for `holder_pubkey_field: Field`.
 *
 * When Midnight exposes an official pubkeyToField() API, replace this.
 */
export function pubkeyToField(pubkeyBytes: Uint8Array): bigint {
  let value = 0n;
  for (let i = 0; i < pubkeyBytes.length; i++) {
    value += BigInt(pubkeyBytes[i]) << BigInt(i * 8);
  }
  return value % PALLAS_SCALAR_PRIME;
}

/** Encode a bigint as a 0x-prefixed hex string (for TicketSecret). */
export function bigintToHex(n: bigint): string {
  return "0x" + n.toString(16);
}

/** Decode a 0x-prefixed hex string to bigint. */
export function hexToBigint(hex: string): bigint {
  return BigInt(hex.startsWith("0x") ? hex : "0x" + hex);
}

/**
 * Generate a cryptographically random Field element to use as a nonce.
 * Works in both browser (crypto.getRandomValues) and Node.js.
 */
function randomNonce(): bigint {
  const buf = new Uint8Array(32);
  if (typeof crypto !== "undefined" && crypto.getRandomValues) {
    crypto.getRandomValues(buf);
  } else {
    // Node.js fallback
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { randomBytes } = require("crypto") as typeof import("crypto");
    const nb = randomBytes(32);
    buf.set(nb);
  }
  return pubkeyToField(buf); // reuse the mod-reduction logic
}

// ─── CompiledContract builder ─────────────────────────────────────────────

/**
 * Build the CompiledContract descriptor used by deployContract /
 * findDeployedContract.
 *
 * TODO: if `@midnight-ntwrk/compact-js` is unavailable, check whether
 *       `@midnight-ntwrk/compact-runtime` exports `CompiledContract`, or
 *       whether `@midnight-ntwrk/midnight-js-contracts` accepts the raw
 *       contract module directly.
 */
async function buildCompiledContract() {
  const mod = await getContractModule();

  // Try compact-js first, fall back to compact-runtime.
  let CompiledContract: {
    make: (name: string, mod: unknown) => unknown;
    withVacantWitnesses: unknown;
    withCompiledFileAssets: (path: string) => unknown;
  };
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    ({ CompiledContract } = require("@midnight-ntwrk/compact-js"));
  } catch {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    ({ CompiledContract } = require("@midnight-ntwrk/compact-runtime"));
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const pipe = (...fns: any[]) => (x: any) => fns.reduce((v, f) => f(v), x);

  return pipe(
    CompiledContract.withVacantWitnesses,
    CompiledContract.withCompiledFileAssets("/contracts/event-tickets"),
  )(CompiledContract.make("event-tickets", mod));
}

// ─── EventTicketAPI ───────────────────────────────────────────────────────

/**
 * High-level wrapper around the compiled event-tickets contract.
 *
 * Usage:
 *
 *   // Deploy a new contract (organizer flow)
 *   const api = await EventTicketAPI.deploy(providers);
 *
 *   // Join an already-deployed contract (attendee flow)
 *   const api = await EventTicketAPI.join(providers, contractAddress);
 *
 *   // Organizer creates the event
 *   await api.createEvent("DevCon 2026", 50);
 *
 *   // Organizer issues a ticket to a holder's pubkey
 *   const result = await api.issueTicket(holderPubkeyHex, 0);
 *   // result.nonce → share with holder off-chain
 *
 *   // Holder proves ownership (ZK proof generated locally)
 *   const { verified } = await api.verifyTicket(ticketId, nonce);
 */
export class EventTicketAPI {
  private constructor(
    private readonly providers: MidnightProviders,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    private readonly _contract: any,
    readonly contractAddress: string,
  ) {}

  // ── Factory: deploy ──────────────────────────────────────────────────────

  /** Deploy a brand-new instance of the event-tickets contract. */
  static async deploy(providers: MidnightProviders): Promise<EventTicketAPI> {
    const compiled = await buildCompiledContract();
    const { contractAddress, txId } = (await deployContract(
      providers,
      compiled,
    )) as DeployResult;
    const contract = await findDeployedContract(
      providers,
      compiled,
      contractAddress,
    );
    console.log(`Contract deployed: ${contractAddress} (txId: ${txId})`);
    return new EventTicketAPI(providers, contract, contractAddress);
  }

  // ── Factory: join ────────────────────────────────────────────────────────

  /** Connect to an already-deployed contract instance. */
  static async join(
    providers: MidnightProviders,
    contractAddress: string,
  ): Promise<EventTicketAPI> {
    const compiled = await buildCompiledContract();
    const contract = await findDeployedContract(
      providers,
      compiled,
      contractAddress,
    );
    return new EventTicketAPI(providers, contract, contractAddress);
  }

  // ── Circuit: create_event ────────────────────────────────────────────────

  /**
   * Initialise the event on-chain.  The caller becomes the organizer.
   *
   * @param name          Human-readable event name (max ~64 chars recommended)
   * @param totalTickets  Maximum number of tickets that may be issued
   */
  async createEvent(
    name: string,
    totalTickets: number,
  ): Promise<{ txId: string }> {
    const { txId } = (await this._contract.callTx.create_event(
      name,
      totalTickets,
    )) as { txId: string };
    return { txId };
  }

  // ── Circuit: issue_ticket ────────────────────────────────────────────────

  /**
   * Issue a ticket to a holder identified by their shielded public key.
   *
   * The organizer must be the wallet's owner (enforced inside the circuit).
   * A fresh random nonce is generated and returned — share it with the holder
   * off-chain (e.g. as a QR code containing the TicketSecret JSON).
   *
   * @param holderPubkeyHex  The holder's shielded public key as a 0x hex string
   * @param ticketId         0-based ticket ordinal
   */
  async issueTicket(
    holderPubkeyHex: string,
    ticketId: number,
  ): Promise<IssueTicketResult> {
    // Decode the holder's public key and convert to a Field element.
    const pubkeyBytes = hexToBytes(holderPubkeyHex);
    const holderPubkeyField = pubkeyToField(pubkeyBytes);
    const nonce = randomNonce();

    const { txId } = (await this._contract.callTx.issue_ticket(
      holderPubkeyField,
      ticketId,
      nonce,
    )) as { txId: string };

    // Recompute commitment locally for the result object (informational only).
    // The actual on-chain commitment is set by the circuit.
    const commitment = simulateCommitment(ticketId, holderPubkeyField, nonce);

    return { txId, ticketId, nonce, commitment };
  }

  // ── Circuit: verify_ticket ───────────────────────────────────────────────

  /**
   * Prove ticket ownership using a ZK proof.
   *
   * The holder supplies the ticketId and nonce from their off-chain ticket
   * secret.  The SDK derives the holder_pubkey_field from the connected
   * wallet's own_public_key() so it is always bound to the caller's identity.
   *
   * @param ticketId  The ticket ordinal from the holder's TicketSecret
   * @param nonce     The random nonce from the holder's TicketSecret
   * @param holderPubkeyField  Field encoding of caller's pubkey (SDK derives
   *                           this; do not accept from untrusted user input)
   */
  async verifyTicket(
    ticketId: number,
    nonce: bigint,
    holderPubkeyField: bigint,
  ): Promise<VerifyTicketResult> {
    const { txId, result } = (await this._contract.callTx.verify_ticket(
      holderPubkeyField,
      ticketId,
      nonce,
    )) as { txId: string; result: boolean };

    return { txId, verified: result };
  }

  // ── Read-only: get state ─────────────────────────────────────────────────

  /** Read the current public on-chain state without submitting a transaction. */
  async getState(): Promise<EventState> {
    // TODO: publicDataProvider.getPublicStates() signature may vary across
    //       SDK versions.  The ledger export from the generated module is
    //       the canonical descriptor; update the call as needed.
    const mod = await getContractModule();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const raw = (await (this.providers.publicDataProvider as any).getPublicStates(
      (mod as any).ledger,
      this.contractAddress,
    )) as Record<string, unknown>;

    const issued = Number(raw["tickets_issued"] ?? 0);
    const rawCommitments = (raw["ticket_commitments"] as unknown[]) ?? [];

    return {
      organizer: raw["organizer"] as Uint8Array,
      eventName: raw["event_name"] as string,
      totalTickets: Number(raw["total_tickets"] ?? 0),
      ticketsIssued: issued,
      commitments: rawCommitments
        .slice(0, issued)
        .map((c) => BigInt(String(c))),
    };
  }
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Decode a 0x-prefixed or plain hex string to a Uint8Array. */
function hexToBytes(hex: string): Uint8Array {
  const clean = hex.startsWith("0x") ? hex.slice(2) : hex;
  if (clean.length % 2 !== 0) throw new Error("Invalid hex string length");
  const bytes = new Uint8Array(clean.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

/**
 * Local (non-ZK) simulation of the on-chain commitment calculation.
 * Used only to populate IssueTicketResult.commitment for UI display.
 * The ZK circuit computes the real commitment using persistent_hash().
 *
 * TODO: implement using the same Poseidon hash variant that Compact uses
 *       once the JS Poseidon implementation is confirmed.  For now, a
 *       simple XOR-fold is used as a placeholder.
 */
function simulateCommitment(
  ticketId: number,
  holderPubkeyField: bigint,
  nonce: bigint,
): bigint {
  // PLACEHOLDER — not cryptographically equivalent to persistent_hash().
  return (BigInt(ticketId) ^ holderPubkeyField ^ nonce) % PALLAS_SCALAR_PRIME;
}
