// ─── Network configuration ─────────────────────────────────────────────────

export const PREPROD_CONFIG = {
  networkId: "preprod" as const,
  indexerUri: "https://indexer.preprod.midnight.network/api/v3/graphql",
  indexerWsUri: "wss://indexer.preprod.midnight.network/api/v3/graphql/ws",
  substrateNodeUri: "wss://rpc.preprod.midnight.network",
  /** Direct URL of the local Docker proof server. */
  proofServerUri: "http://localhost:6300",
};

export type NetworkConfig = typeof PREPROD_CONFIG;

// ─── Proof server proxy base (Next.js API routes) ──────────────────────────
export const PROOF_SERVER_PROXY_BASE = "/api/proof";

// ─── Contract-level types ──────────────────────────────────────────────────

/** Public on-chain state decoded from the indexer. */
export interface EventState {
  /** Organizer's shielded public key (32 bytes). */
  organizer: Uint8Array;
  /** Human-readable event name. */
  eventName: string;
  /** Maximum tickets declared at event creation. */
  totalTickets: number;
  /** Number of tickets issued so far. */
  ticketsIssued: number;
  /**
   * On-chain commitment vector, trimmed to ticketsIssued entries.
   * Each element is  persistent_hash(ticket_id ‖ holder_pubkey_field ‖ nonce).
   */
  commitments: bigint[];
}

// ─── API call results ─────────────────────────────────────────────────────

export interface DeployResult {
  contractAddress: string;
  txId: string;
}

export interface IssueTicketResult {
  txId: string;
  ticketId: number;
  /**
   * Random nonce generated by the SDK.
   * Share this with the ticket holder off-chain (e.g. in a QR code).
   * The holder needs it to call verifyTicket().
   */
  nonce: bigint;
  /** The on-chain Poseidon commitment (for reference / audit). */
  commitment: bigint;
}

export interface VerifyTicketResult {
  verified: boolean;
  txId: string;
}

// ─── Off-chain ticket secret (share with holder) ──────────────────────────

/**
 * Serialisable bundle that the organizer sends to the holder.
 * The holder imports this into the verify-ticket page to prove ownership.
 */
export interface TicketSecret {
  contractAddress: string;
  ticketId: number;
  /** hex-encoded bigint */
  nonce: string;
  /**
   * hex-encoded Field representation of the holder's pubkey.
   * Stored here so the holder's browser can reconstruct the commitment.
   */
  holderPubkeyField: string;
}
