// ─── Network configuration ─────────────────────────────────────────────────

export const PREPROD_CONFIG = {
  networkId: "preprod" as const,
  indexerUri: "https://indexer.preprod.midnight.network/api/v3/graphql",
  indexerWsUri: "wss://indexer.preprod.midnight.network/api/v3/graphql/ws",
  substrateNodeUri: "wss://rpc.preprod.midnight.network",
  /** Direct URL of the local Docker proof server. */
  proofServerUri: "http://localhost:6300",
};

export type NetworkConfig = typeof PREPROD_CONFIG;

// ─── Proof server proxy base (Next.js API routes) ──────────────────────────
export const PROOF_SERVER_PROXY_BASE = "/api/proof";

// ─── Contract-level types ──────────────────────────────────────────────────

/** Public on-chain state decoded from the indexer. */
export interface EventState {
  /** Organizer's identity commitment (hash of their secret). */
  organizer: Uint8Array;
  /** Human-readable event name, decoded from the on-chain Bytes<32>. */
  eventName: string;
  /** Maximum tickets declared at event creation. */
  totalTickets: bigint;
  /** Number of tickets claimed so far (from Counter ledger field). */
  ticketsIssued: bigint;
  /** False when the event is paused or cancelled. */
  isActive: boolean;
  /** True when the event has been permanently cancelled. */
  isCancelled: boolean;
  /** Minimum attendee age (0 = no restriction). */
  minAge: bigint;
}

// ─── API call results ─────────────────────────────────────────────────────

export interface DeployResult {
  contractAddress: string;
  txId: string;
}

export interface ClaimTicketResult {
  txId: string;
  /**
   * Random Field nonce generated by the SDK witness.
   * Stored in the attendee's browser as their private ticket secret.
   * The attendee supplies this nonce to verify_ticket() / admit_ticket().
   */
  nonce: bigint;
}

export interface VerifyTicketResult {
  /** true = ticket is valid AND has not been admitted yet */
  verified: boolean;
  txId: string;
}

export interface AdmitTicketResult {
  txId: string;
}

/**
 * Returned by grantDelegate().
 * The organizer MUST share `delegateSecret` with the co-manager via a secure
 * channel.  The co-manager passes it to EventTicketAPI.join() as callerSecret.
 */
export interface GrantDelegateResult {
  txId: string;
  /** Raw scalar the delegate must use as their caller_secret. */
  delegateSecret: bigint;
}

// ─── Off-chain ticket secret (stored in attendee's browser) ───────────────

/**
 * Serialisable bundle stored in the attendee's localStorage.
 * Encoded into a QR code for venue scanning / self-verification.
 */
export interface TicketSecret {
  contractAddress: string;
  /** hex-encoded bigint nonce (the witness secret) */
  nonce: string;
}
