// ─── Network configuration ─────────────────────────────────────────────────

export const PREPROD_CONFIG = {
  networkId: "preprod" as const,
  indexerUri: "https://indexer.preprod.midnight.network/api/v3/graphql",
  indexerWsUri: "wss://indexer.preprod.midnight.network/api/v3/graphql/ws",
  substrateNodeUri: "wss://rpc.preprod.midnight.network",
  /** Direct URL of the local Docker proof server. */
  proofServerUri: "http://localhost:6300",
};

export type NetworkConfig = typeof PREPROD_CONFIG;

// ─── Proof server proxy base (Next.js API routes) ──────────────────────────
export const PROOF_SERVER_PROXY_BASE = "/api/proof";

// ─── Contract-level types ──────────────────────────────────────────────────

/** Public on-chain state decoded from the indexer. */
export interface EventState {
  /** Organizer's shielded public key (32 bytes). */
  organizer: Uint8Array;
  /** Human-readable event name, decoded from the on-chain Bytes<32>. */
  eventName: string;
  /** Maximum tickets declared at event creation. */
  totalTickets: bigint;
  /** Number of tickets issued so far (from Counter ledger field). */
  ticketsIssued: bigint;
}

// ─── API call results ─────────────────────────────────────────────────────

export interface DeployResult {
  contractAddress: string;
  txId: string;
}

export interface IssueTicketResult {
  txId: string;
  /**
   * Random Field nonce generated by the SDK witness.
   * Share this with the ticket holder off-chain (e.g. in a QR code or email).
   * The holder supplies this nonce to verifyTicket() to prove ownership.
   */
  nonce: bigint;
}

export interface VerifyTicketResult {
  verified: boolean;
  txId: string;
}

// ─── Off-chain ticket secret (share with holder) ──────────────────────────

/**
 * Serialisable bundle that the organizer sends to the ticket holder.
 * The holder imports this into the verify-ticket page to prove ownership.
 */
export interface TicketSecret {
  contractAddress: string;
  /** hex-encoded bigint nonce (the witness secret) */
  nonce: string;
}
